import type { LearningCopy } from "@/domain/learning/types";

export const learningCopy = {
	label: { en: "Interactive practice", zh: "互动练习" },
	synthetic: { en: "Synthetic cases", zh: "模拟案例" },
	stages: { en: "3 stages", zh: "3 个阶段" },
	start: { en: "Start or resume practice", zh: "开始或继续练习" },
	saving: { en: "Saving your decision…", zh: "正在保存你的判断…" },
	loading: { en: "Opening your case…", zh: "正在打开案例…" },
	saved: { en: "Saved to your account", zh: "已保存到你的账户" },
	previewOnly: {
		en: "Preview only · decisions reset on reload",
		zh: "仅供预览 · 刷新后判断会重置",
	},
	prediction: { en: "First judgment", zh: "初步判断" },
	guided: { en: "Investigate", zh: "检查证据" },
	independent: { en: "Independent case", zh: "独立案例" },
	evidence: { en: "Evidence to inspect", zh: "待检查的证据" },
	inspected: { en: "Inspected", zh: "已检查" },
	initial: { en: "Your initial judgment", zh: "你的初步判断" },
	judgment: { en: "Your judgment", zh: "你的判断" },
	help: { en: "Show a hint", zh: "查看提示" },
	hint: { en: "A question to guide your check", zh: "帮助你检查的问题" },
	commit: { en: "Commit my judgment", zh: "提交初步判断" },
	submit: { en: "Review my reasoning", zh: "检查我的推理" },
	next: { en: "Continue investigation", zh: "继续检查" },
	independentNext: { en: "Try the independent case", zh: "进入独立案例" },
	incomplete: {
		en: "Inspect the evidence and answer every question to continue.",
		zh: "检查证据并回答所有问题后即可继续。",
	},
	debrief: { en: "What the evidence supports", zh: "证据支持什么" },
	met: { en: "Supported", zh: "有证据支持" },
	revisit: { en: "Revisit this reasoning", zh: "重新检查这项推理" },
	yourAnswer: { en: "Your answer", zh: "你的答案" },
	demonstrated: { en: "Demonstrated in this case", zh: "已在本案例中独立掌握" },
	practiced: { en: "Practice completed", zh: "练习已完成" },
	criteria: { en: "Independent criteria met", zh: "满足的独立判断标准" },
	hinted: {
		en: "You used a hint on the independent case. This result is saved as practice.",
		zh: "你在独立案例中使用了提示，因此本次结果记录为练习。",
	},
	completeNote: {
		en: "This practice result is separate from your course completion and video progress.",
		zh: "本次练习结果与课程完成情况及视频进度分别记录。",
	},
	tryAgain: { en: "Practice another case", zh: "练习另一个案例" },
	retry: { en: "Retry saving", zh: "重试保存" },
	retryOpen: { en: "Try again", zh: "重试" },
	reload: { en: "Load latest attempt", zh: "加载最新练习" },
	restart: { en: "Start the updated case", zh: "开始更新后的案例" },
	errorTitle: { en: "Practice needs attention", zh: "练习需要处理" },
	unavailable: {
		en: "Practice is temporarily unavailable. Retry to continue; your course completion and video progress are unchanged.",
		zh: "练习暂时无法使用。请重试后继续；课程完成情况和视频进度不受影响。",
	},
	conflict: {
		en: "This attempt changed in another tab. Load the latest version before making another decision.",
		zh: "这次练习已在其他标签页中更新。请加载最新版本后继续判断。",
	},
	retired: {
		en: "This case has been updated. Your previous attempt is preserved; start the current case to continue.",
		zh: "案例已更新。之前的练习记录会保留，请开始当前案例。",
	},
	signed_out: {
		en: "Sign in again to open your saved practice.",
		zh: "请重新登录以打开已保存的练习。",
	},
	access_denied: {
		en: "Your account does not currently have access to this lesson. Check your course access before continuing.",
		zh: "你的账户目前没有本课权限，请检查课程访问资格后继续。",
	},
	not_found: {
		en: "This practice is not available for the current account or lesson.",
		zh: "当前账户或课程无法访问该练习。",
	},
	invalid_action: {
		en: "That decision could not be applied. Load your latest saved attempt and try again.",
		zh: "无法应用这项判断。请加载最新保存的练习后重试。",
	},
	quoteAxis: { en: "Option price (USD)", zh: "期权价格（美元）" },
	bid: { en: "Bid", zh: "买价" },
	ask: { en: "Ask", zh: "卖价" },
	trade: { en: "Execution", zh: "成交" },
} satisfies Record<string, LearningCopy>;
