export const courseModules = [
	{ id: "contracts", en: "Contracts and money", zh: "合约与金额" },
	{
		id: "execution",
		en: "Quotes, executions and sentiment",
		zh: "报价、成交与情绪分类",
	},
	{
		id: "flow",
		en: "Flow, positions and data quality",
		zh: "成交流、持仓与数据质量",
	},
	{
		id: "exposure",
		en: "Pricing, Greeks and exposure",
		zh: "定价、希腊值与敞口",
	},
	{
		id: "structure",
		en: "Modeled positioning and structure",
		zh: "模型持仓与结构",
	},
	{ id: "research", en: "Comparison and investigation", zh: "比较与研究" },
	{ id: "production", en: "Produce and audit research", zh: "撰写与审核研究" },
	{ id: "portfolio", en: "Portfolio understanding", zh: "理解投资组合" },
] as const;
export type ModuleId = (typeof courseModules)[number]["id"];

type Entry = {
	id: string;
	moduleId: ModuleId;
	title: string;
	titleZh: string;
	summary: string;
	summaryZh: string;
	concepts: string[];
	prerequisites: string[];
};
const lesson = (
	id: string,
	moduleId: ModuleId,
	title: string,
	titleZh: string,
	summary: string,
	summaryZh: string,
	concepts: string[],
	prerequisites: string[] = [],
): Entry => ({
	id,
	moduleId,
	title,
	titleZh,
	summary,
	summaryZh,
	concepts,
	prerequisites,
});
export const syllabus: readonly Entry[] = [
	lesson(
		"option-contracts",
		"contracts",
		"What an option contract describes",
		"期权合约描述什么",
		"Identify the underlying, contract, units and source date.",
		"识别标的、合约、单位与来源日期。",
		["C01", "C02"],
	),
	lesson(
		"option-rights",
		"contracts",
		"Buyers, writers, rights and obligations",
		"买方、卖方、权利与义务",
		"Separate long and short calls and puts from buying and selling shares.",
		"区分看涨与看跌期权的多空持仓，以及股票买卖。",
		["C02", "C09"],
		["option-contracts"],
	),
	lesson(
		"premium-payoff",
		"contracts",
		"Price, premium, payoff and profit",
		"价格、权利金、到期价值与盈亏",
		"Calculate premium, moneyness and profit with explicit units.",
		"使用明确单位计算权利金、价内外状态与盈亏。",
		["C03"],
		["option-rights"],
	),
	lesson(
		"expiration-settlement",
		"contracts",
		"Expiration, exercise and settlement",
		"到期、行权与结算",
		"Distinguish closing a trade from exercise, assignment and settlement.",
		"区分平仓交易、行权、被指派与结算。",
		["C02", "C24"],
		["premium-payoff"],
	),
	lesson(
		"quotes-orders-trades",
		"execution",
		"A quote, an order and a trade",
		"报价、订单与成交",
		"Read bid, ask, size, spread and last without inventing a fill.",
		"阅读买价、卖价、数量、价差和最新成交，避免虚构成交。",
		["C04"],
		["premium-payoff"],
	),
	lesson(
		"execution-counterparties",
		"execution",
		"Who buys and who sells in one execution?",
		"同一笔成交中谁买谁卖？",
		"Follow an incoming order into a resting counterparty and one print.",
		"跟随主动订单与挂单方撮合，形成一笔成交。",
		["C05"],
		["quotes-orders-trades"],
	),
	lesson(
		"execution-side",
		"execution",
		"Read execution side against a reliable quote",
		"用可靠报价判断成交位置",
		"Classify bid, inside-spread and ask executions; preserve uncertainty.",
		"分类买价、价差内与卖价成交，并保留不确定性。",
		["C06", "C24"],
		["execution-counterparties"],
	),
	lesson(
		"flow-sentiment",
		"execution",
		"How flow gets a bullish or bearish label",
		"成交流如何获得看涨或看跌标签",
		"Connect option type to inferred direction without claiming a whole strategy.",
		"结合期权类型推断方向，不把单腿分类当作完整策略。",
		["C07"],
		["execution-side", "option-rights"],
	),
	lesson(
		"validate-option-print",
		"execution",
		"Validate one execution from its evidence",
		"用证据验证一笔成交",
		"Calculate premium and separate facts, inference, unknowns and next checks.",
		"计算权利金，区分事实、推断、未知与下一项检查。",
		["C03", "C06", "C07", "C24"],
		["flow-sentiment"],
	),
	lesson(
		"session-flow-vs-structure",
		"flow",
		"Why volume and open interest move differently",
		"成交量与未平仓量为何变化不同",
		"Build two ledgers and compare reports for the same contract cohort.",
		"建立两本台账，比较同一合约集合的报告。",
		["C08", "C24"],
		["validate-option-print"],
	),
	lesson(
		"trade-records",
		"flow",
		"What a tape row represents",
		"成交记录中的一行代表什么",
		"Reconstruct size, premium and count; interpret execution conditions.",
		"还原数量、权利金与笔数，并解读成交条件。",
		["C10", "C11"],
		["execution-side"],
	),
	lesson(
		"unusual-activity",
		"flow",
		"When activity is actually unusual",
		"什么时候成交确实异常",
		"Compare activity with the correct baseline and denominator.",
		"使用正确基准与分母比较成交活跃度。",
		["C12", "C25"],
		["session-flow-vs-structure"],
	),
	lesson(
		"option-strategies",
		"flow",
		"One leg can belong to many strategies",
		"一条期权腿可以属于多种策略",
		"Distinguish a leg's directional effect from portfolio intent and risk.",
		"区分单腿方向影响与组合意图、风险。",
		["C09"],
		["flow-sentiment"],
	),
	lesson(
		"symbol-drawer",
		"flow",
		"Read each source on its own clock",
		"按各自时间阅读每个来源",
		"Audit identity, dates, coverage and fixed versus rolling cohorts.",
		"审核身份、日期、覆盖及固定与滚动合约集合。",
		["C24"],
		["session-flow-vs-structure"],
	),
	lesson(
		"delta",
		"exposure",
		"Delta: a local price sensitivity",
		"Delta：局部价格敏感度",
		"Calculate a small-move approximation and distinguish position signs.",
		"计算小幅变动近似值，区分持仓方向。",
		["C13"],
		["premium-payoff"],
	),
	lesson(
		"gamma",
		"exposure",
		"Gamma: how delta changes",
		"Gamma：Delta 如何变化",
		"Explain curvature and a conditional hedge adjustment.",
		"解释曲率及有条件的对冲调整。",
		["C13"],
		["delta"],
	),
	lesson(
		"theta-vega-rho",
		"exposure",
		"Time, volatility and rates",
		"时间、波动率与利率",
		"Read theta, vega and rho in their own units and assumptions.",
		"按各自单位与假设阅读 Theta、Vega 和 Rho。",
		["C13"],
		["delta"],
	),
	lesson(
		"implied-realized-volatility",
		"exposure",
		"Implied and realized volatility",
		"隐含波动率与已实现波动率",
		"Distinguish model-implied prices from measured historical returns.",
		"区分价格反推的模型值与历史收益测量值。",
		["C14"],
		["theta-vega-rho"],
	),
	lesson(
		"volatility-surface",
		"exposure",
		"Smile, skew and term structure",
		"微笑、偏斜与期限结构",
		"Read strike and expiry slices while preserving missing observations.",
		"阅读行权价和到期切片，同时保留缺失观测。",
		["C15"],
		["implied-realized-volatility"],
	),
	lesson(
		"iv-rank-percentile",
		"exposure",
		"IV rank and percentile can disagree",
		"IV Rank 与百分位可以不同",
		"Compute range position and historical frequency separately.",
		"分别计算区间位置与历史频率。",
		["C16"],
		["implied-realized-volatility"],
	),
	lesson(
		"dex-dei-gex",
		"exposure",
		"From delta equivalents to DEX and DEI",
		"从 Delta 等价量到 DEX 与 DEI",
		"Separate magnitude, signed flow and liquidity normalization.",
		"区分幅度、带符号成交流与流动性归一化。",
		["C17", "C18"],
		["delta", "unusual-activity"],
	),
	lesson(
		"gamma-exposure",
		"structure",
		"Build and interpret a GEX snapshot",
		"建立并解读 GEX 快照",
		"Compare net, gross and local exposure under stated model signs.",
		"在给定模型符号下比较净值、总幅度与局部敞口。",
		["C19"],
		["gamma", "session-flow-vs-structure"],
	),
	lesson(
		"gamma-regimes",
		"structure",
		"Gamma regimes and the zero-gamma boundary",
		"Gamma 状态与零 Gamma 边界",
		"Explain conditional hedging without turning modeled levels into forecasts.",
		"解释有条件的对冲，避免把模型位置变成预测。",
		["C20"],
		["gamma-exposure"],
	),
	lesson(
		"structural-levels",
		"structure",
		"Walls, concentration, max pain and distance",
		"墙位、集中度、最大痛点与距离",
		"Distinguish gamma-weighted references from an OI-only payout model.",
		"区分 Gamma 加权参考与仅基于 OI 的到期支付模型。",
		["C21"],
		["gamma-exposure"],
	),
	lesson(
		"charm-vanna",
		"structure",
		"Exposure changes without a new trade",
		"没有新成交，敞口也会改变",
		"Separate time, volatility and spot effects using charm and vanna.",
		"使用 Charm 和 Vanna 区分时间、波动率与现价影响。",
		["C22"],
		["gamma", "theta-vega-rho"],
	),
	lesson(
		"audited-boundary",
		"research",
		"Write a question the evidence can answer",
		"写出证据能回答的问题",
		"Declare an observable question, inputs and a reason to reconsider.",
		"声明可观察的问题、输入与重新考虑的条件。",
		["C26"],
		["symbol-drawer"],
	),
	lesson(
		"symbol-universe",
		"research",
		"Define who belongs in the comparison",
		"明确谁属于比较范围",
		"Derive eligibility from raw facts and keep exclusions visible.",
		"从原始事实判断资格，并保留可见排除项。",
		["C23", "C24"],
		["audited-boundary"],
	),
	lesson(
		"rank-symbols",
		"research",
		"Rank observations without inventing a prediction",
		"排名观测，不虚构预测",
		"Choose a metric for the question and explain peer-driven rank changes.",
		"为问题选择指标，并解释同组数据引起的排名变化。",
		["C12", "C23"],
		["symbol-universe"],
	),
	lesson(
		"rank-contracts",
		"research",
		"Read a contract neighborhood",
		"阅读合约邻域",
		"Compare concentration and total activity across strikes and expiries.",
		"比较行权价与到期日之间的集中度和总成交。",
		["C03", "C23"],
		["rank-symbols", "premium-payoff"],
	),
	lesson(
		"point-in-time-research",
		"research",
		"Test a pattern without hindsight",
		"避免后见之明，检验模式",
		"Keep a fixed rule, point-in-time inputs and an unseen evaluation period.",
		"保留固定规则、当时可用输入与未见评估时段。",
		["C25", "C26"],
		["rank-contracts"],
	),
	lesson(
		"cookbook-research-packet",
		"production",
		"Build a reproducible research packet",
		"建立可重现的研究包",
		"Write inputs, calculations, exclusions and a rerunnable method.",
		"写下输入、计算、排除项与可重跑方法。",
		["C27"],
		["point-in-time-research"],
	),
	lesson(
		"market-recap",
		"production",
		"Write a supported recap",
		"撰写有依据的复盘",
		"Produce a headline, chart, evidence references and visible caveats.",
		"生成标题、图表、证据引用与可见限制。",
		["C27"],
		["cookbook-research-packet"],
	),
	lesson(
		"audit-market-recap",
		"production",
		"Audit and repair an unfamiliar recap",
		"审核并修复陌生复盘",
		"Find numerical and inference defects while retaining supported claims.",
		"发现数值与推断缺陷，同时保留有依据的结论。",
		["C26", "C27"],
		["market-recap"],
	),
	lesson(
		"portfolio-pnl",
		"portfolio",
		"Positions, cost, cash and P&L",
		"持仓、成本、现金与盈亏",
		"Calculate position value, realized/unrealized P&L and concentration.",
		"计算持仓价值、已实现与未实现盈亏及集中度。",
		["C28"],
		["option-strategies"],
	),
	lesson(
		"portfolio-performance",
		"portfolio",
		"Evaluate performance rather than balance growth",
		"评价表现，而非只看余额增长",
		"Separate cash flows from returns and inspect performance statistics.",
		"区分资金流与收益，并检验绩效统计。",
		["C29"],
		["portfolio-pnl"],
	),
	lesson(
		"portfolio-exposure",
		"portfolio",
		"Aggregate portfolio exposure and its limits",
		"汇总组合敞口及其限制",
		"Sum position Greeks with correct signs, multipliers and coverage.",
		"使用正确符号、乘数与覆盖范围汇总持仓希腊值。",
		["C30"],
		["portfolio-pnl", "theta-vega-rho", "gamma"],
	),
];
