export const courseModules = [
	{
		id: "contracts",
		path: "core",
		en: "Contracts and money",
		zh: "合约与金额",
	},
	{
		id: "execution",
		path: "core",
		en: "Quotes, executions and sentiment",
		zh: "报价、成交与情绪分类",
	},
	{
		id: "flow",
		path: "core",
		en: "Flow, positions and data quality",
		zh: "成交流、持仓与数据质量",
	},
	{
		id: "research",
		path: "core",
		en: "Comparison and investigation",
		zh: "比较与研究",
	},
	{
		id: "production",
		path: "core",
		en: "Produce and audit research",
		zh: "撰写与审核研究",
	},
	{
		id: "exposure",
		path: "models",
		en: "Greeks, volatility and exposure",
		zh: "希腊值、波动率与敞口",
	},
	{
		id: "structure",
		path: "models",
		en: "Modeled positioning and structure",
		zh: "模型持仓与结构",
	},
	{
		id: "portfolio",
		path: "portfolio",
		en: "Portfolio understanding",
		zh: "理解投资组合",
	},
] as const;
/** The core path runs in lesson order; the two deeper branches follow it in either order. */
export const coursePaths = {
	core: { en: "Core path", zh: "核心路径" },
	models: {
		en: "Deeper branch: Greeks, volatility and structure",
		zh: "深入分支：希腊值、波动率与结构",
	},
	portfolio: { en: "Deeper branch: portfolios", zh: "深入分支：投资组合" },
} as const;
export type CoursePathId = keyof typeof coursePaths;
export type ModuleId = (typeof courseModules)[number]["id"];

type Entry = {
	id: string;
	moduleId: ModuleId;
	title: string;
	titleZh: string;
	summary: string;
	summaryZh: string;
	concepts: string[];
	prerequisites: string[];
};
const lesson = (
	id: string,
	moduleId: ModuleId,
	title: string,
	titleZh: string,
	summary: string,
	summaryZh: string,
	concepts: string[],
	prerequisites: string[] = [],
): Entry => ({
	id,
	moduleId,
	title,
	titleZh,
	summary,
	summaryZh,
	concepts,
	prerequisites,
});
export const syllabus: readonly Entry[] = [
	lesson(
		"option-contracts",
		"contracts",
		"Option contracts: what you are buying",
		"期权合约：你买的是什么",
		"Identify a contract from its underlying, type, strike and expiry, and turn a quoted price into dollars.",
		"从标的、类型、行权价与到期日识别一份合约，并把报价换算成金额。",
		["C01", "C02"],
	),
	lesson(
		"option-rights",
		"contracts",
		"Holders and writers: rights and obligations",
		"持有人与义务方：权利和义务",
		"See who holds the right, who carries the obligation, and how trading an option differs from exercising it.",
		"认清谁拥有权利、谁承担义务，以及交易期权与行权有何不同。",
		["C02", "C09"],
		["option-contracts"],
	),
	lesson(
		"premium-payoff",
		"contracts",
		"Premium, payoff and profit: both sides of the trade",
		"权利金、到期价值与盈亏：交易的两方",
		"Calculate premium, payoff and profit for the buyer and the writer, and see why in the money can still lose.",
		"计算买方与义务方的权利金、到期价值与盈亏，理解为何实值也可能亏损。",
		["C03"],
		["option-rights"],
	),
	lesson(
		"expiration-settlement",
		"contracts",
		"Expiration: exercise, assignment and settlement",
		"到期：行权、指派与结算",
		"Tell closing from exercise and assignment, settle physical and cash contracts, and spot expiry-day surprises.",
		"区分平仓、行权与指派，完成实物与现金结算，并识别到期日的意外。",
		["C02", "C24"],
		["premium-payoff"],
	),
	lesson(
		"quotes-orders-trades",
		"execution",
		"Quotes, orders and trades: three different events",
		"报价、订单与成交：三种不同事件",
		"Read bid, ask, sizes, spread and last without mistaking a quote for a fill.",
		"读懂买价、卖价、数量、价差与最新价，不把报价当成成交。",
		["C04"],
		["premium-payoff"],
	),
	lesson(
		"execution-counterparties",
		"execution",
		"Counterparties: who buys and who sells in one trade",
		"交易对手：同一笔成交中谁买谁卖",
		"Follow one incoming order into a resting order: two participants, one trade.",
		"追踪一张主动订单与挂单撮合：两方参与，一笔成交。",
		["C05"],
		["quotes-orders-trades"],
	),
	lesson(
		"execution-side",
		"execution",
		"Execution side: where a trade printed against the quote",
		"成交位置：成交价相对报价的位置",
		"Classify a trade as at the bid, inside the spread or at the ask, and know when the quote is too stale to tell.",
		"判断成交位于买价、价差内或卖价，并识别报价过旧、无法判断的情况。",
		["C06", "C24"],
		["execution-counterparties"],
	),
	lesson(
		"flow-sentiment",
		"execution",
		"Sentiment labels: when bullish or bearish is justified",
		"情绪标签：何时能称为看涨或看跌",
		"Learn when it is fair to call a trade bullish or bearish, and what that label cannot tell you.",
		"了解何时可以把一笔成交称为看涨或看跌，以及该标签无法说明什么。",
		["C07"],
		["execution-side"],
	),
	lesson(
		"validate-option-print",
		"execution",
		"Checking one trade: facts, inferences and unknowns",
		"核查一笔成交：事实、推断与未知",
		"Work through one trade from its evidence: premium, side, what is known and what to check next.",
		"从证据出发检查一笔成交：权利金、成交位置、已知信息与下一步检查。",
		["C03", "C06", "C07", "C24"],
		["flow-sentiment"],
	),
	lesson(
		"session-flow-vs-structure",
		"flow",
		"Volume and open interest: why they move differently",
		"成交量与未平仓量：为何变化不同",
		"See how opening, closing and transferred contracts move volume and open interest differently.",
		"理解开仓、平仓与转移如何让成交量与未平仓量发生不同变化。",
		["C08", "C24"],
		["validate-option-print", "expiration-settlement"],
	),
	lesson(
		"trade-records",
		"flow",
		"Tape rows: what one record represents",
		"成交记录：一行代表什么",
		"Rebuild size, premium and count from source prints, and follow duplicate and corrected messages.",
		"从原始成交还原数量、权利金与笔数，并追踪重复与更正消息。",
		["C10"],
		["execution-side"],
	),
	lesson(
		"execution-conditions",
		"flow",
		"Sweeps, blocks and complex orders: how a trade executed",
		"扫单、大宗与复杂订单：成交如何执行",
		"Read what sweep, block and multi-leg conditions say about how a trade executed, and what they leave unknown.",
		"读懂扫单、大宗与多腿条件说明了成交如何执行，以及仍然未知的部分。",
		["C11"],
		["trade-records"],
	),
	lesson(
		"unusual-activity",
		"flow",
		"Unusual activity: compared with what?",
		"异常成交：与什么相比？",
		"Compare activity with the right baseline, and see how a tiny denominator fakes a spike.",
		"用正确基准比较成交活跃度，并看清极小分母如何制造假异常。",
		["C12", "C25"],
		["session-flow-vs-structure"],
	),
	lesson(
		"option-strategies",
		"flow",
		"Strategies: one leg, many possible positions",
		"策略：一条腿，多种可能的持仓",
		"See how spreads, covered calls, collars and rolls change what one option leg means.",
		"看价差、备兑、领口与移仓如何改变单条期权腿的含义。",
		["C09"],
		["flow-sentiment"],
	),
	lesson(
		"symbol-drawer",
		"flow",
		"Data clocks: when each source was true",
		"数据时钟：每个来源在何时成立",
		"Check each field's source, time and coverage before combining data from different clocks.",
		"组合不同时间的数据前，先检查每个字段的来源、时间与覆盖。",
		["C24"],
		["session-flow-vs-structure"],
	),
	lesson(
		"audited-boundary",
		"research",
		"Research questions: what evidence can answer",
		"研究问题：证据能回答什么",
		"Frame a question with a clear subject, measure and time window, and a reason to revisit it.",
		"提出对象、测量量与时间窗口都明确的问题，并说明何时需要重新审视。",
		["C26"],
		["symbol-drawer"],
	),
	lesson(
		"symbol-universe",
		"research",
		"Comparison groups: who belongs and who is missing",
		"比较范围：谁该纳入，谁缺失",
		"Decide from raw facts which names belong in a comparison, and keep missing ones visible.",
		"依据原始事实决定哪些标的进入比较，并让缺失项保持可见。",
		["C01", "C23", "C24"],
		["audited-boundary"],
	),
	lesson(
		"rank-symbols",
		"research",
		"Rankings: order without prediction",
		"排名：排序不等于预测",
		"Pick a ranking metric for your question, and see how peers can move a rank without new activity.",
		"为问题选择排名指标，并看同组变化如何在没有新成交时改变排名。",
		["C12", "C23"],
		["symbol-universe"],
	),
	lesson(
		"rank-contracts",
		"research",
		"Contract neighborhoods: strikes and expiries in context",
		"合约邻域：结合行权价与到期日来看",
		"Compare total activity and concentration across strikes and expiries before choosing a contract to inspect.",
		"选择要检查的合约前，先比较不同行权价与到期日的总成交与集中度。",
		["C03", "C23"],
		["rank-symbols"],
	),
	lesson(
		"point-in-time-research",
		"research",
		"Backtests: testing a pattern without hindsight",
		"回测：不带后见之明地检验模式",
		"Test an idea only on data you have not looked at, using what was known at the time.",
		"只用当时已知的信息，并只在未看过的数据上检验一个想法。",
		["C25", "C26"],
		["rank-contracts"],
	),
	lesson(
		"cookbook-research-packet",
		"production",
		"Research packets: work someone else can rerun",
		"研究包：他人可以重跑的工作",
		"Record inputs, calculations and exclusions so someone else can rerun your result.",
		"记录输入、计算与排除项，让他人能够重跑你的结果。",
		["C27"],
		["point-in-time-research"],
	),
	lesson(
		"market-recap",
		"production",
		"Recaps: claims your evidence supports",
		"复盘：证据支持的结论",
		"Build a headline, chart and caption that say only what the evidence supports.",
		"撰写只陈述证据所支持内容的标题、图表与图注。",
		["C27"],
		["cookbook-research-packet"],
	),
	lesson(
		"audit-market-recap",
		"production",
		"Audits: finding and repairing a flawed recap",
		"审核：发现并修复有缺陷的复盘",
		"Find the numerical and reasoning errors in someone else's recap, fix them, and keep what holds up.",
		"找出他人复盘中的数值与推理错误，加以修复，并保留成立的部分。",
		["C26", "C27"],
		["market-recap"],
	),
	lesson(
		"delta",
		"exposure",
		"Delta: a local price sensitivity",
		"Delta：局部价格敏感度",
		"Estimate how an option's price moves for a small stock move, and get the position's sign right.",
		"估算标的小幅变动时期权价格的变化，并确定持仓的正负方向。",
		["C13"],
		["premium-payoff"],
	),
	lesson(
		"gamma",
		"exposure",
		"Gamma: how delta changes",
		"Gamma：Delta 如何变化",
		"See how delta itself changes as the stock moves, and what that means for a hedge.",
		"理解 Delta 如何随股价变化，以及这对对冲意味着什么。",
		["C13"],
		["delta"],
	),
	lesson(
		"theta-vega-rho",
		"exposure",
		"Theta, vega and rho: time, volatility and rates",
		"Theta、Vega 与 Rho：时间、波动率与利率",
		"Read time decay, volatility and rate sensitivity in their own units, and see how they can outweigh a good move.",
		"按各自单位读取时间损耗、波动率与利率敏感度，并看它们如何抵消有利的价格变动。",
		["C13"],
		["delta"],
	),
	lesson(
		"implied-realized-volatility",
		"exposure",
		"Implied and realized volatility: forward and backward views",
		"隐含与已实现波动率：向前与向后的视角",
		"Tell the volatility priced into options from the volatility the stock actually showed.",
		"区分期权价格中隐含的波动率与股票实际表现出的波动率。",
		["C14"],
		["theta-vega-rho"],
	),
	lesson(
		"volatility-surface",
		"exposure",
		"The volatility surface: smile, skew and term structure",
		"波动率曲面：微笑、偏斜与期限结构",
		"Read implied volatility across strikes and expiries, and tell measured points from filled-in ones.",
		"按行权价与到期日读取隐含波动率，并区分实际观测与插值估计。",
		["C15"],
		["implied-realized-volatility"],
	),
	lesson(
		"iv-rank-percentile",
		"exposure",
		"IV rank and percentile: why they disagree",
		"IV Rank 与百分位：为何会不同",
		"Compute IV rank and IV percentile on the same history, and see why one outlier splits them.",
		"在同一历史上计算 IV Rank 与 IV 百分位，并看一个极端值为何让两者分歧。",
		["C16"],
		["implied-realized-volatility"],
	),
	lesson(
		"dex-dei-gex",
		"exposure",
		"DEX and DEI: flow in share-equivalents",
		"DEX 与 DEI：以股等价量衡量成交流",
		"Turn trades into share-equivalents and compare flow across stocks of different sizes.",
		"把成交换算成股等价量，并在规模不同的股票之间比较成交流。",
		["C17", "C18"],
		["delta", "unusual-activity"],
	),
	lesson(
		"gamma-exposure",
		"structure",
		"GEX: building a gamma exposure snapshot",
		"GEX：建立 Gamma 敞口快照",
		"Build a GEX snapshot from stated assumptions, and compare net, gross and local exposure.",
		"在明确假设下建立 GEX 快照，并比较净值、总幅度与局部敞口。",
		["C19"],
		["gamma", "volatility-surface", "symbol-drawer"],
	),
	lesson(
		"gamma-regimes",
		"structure",
		"Gamma regimes: hedging, not forecasting",
		"Gamma 状态：对冲，而非预测",
		"See how hedging flows differ above and below the zero-gamma level, without treating it as a forecast.",
		"理解零 Gamma 位置上下的对冲流有何不同，而不把它当作预测。",
		["C20"],
		["gamma-exposure"],
	),
	lesson(
		"structural-levels",
		"structure",
		"Walls and max pain: reference levels, not targets",
		"墙位与最大痛点：参考位置，不是目标",
		"Tell gamma walls from max pain, and measure distance in dollars, percent and ATR.",
		"区分 Gamma 墙位与最大痛点，并用美元、百分比与 ATR 衡量距离。",
		["C21"],
		["gamma-exposure"],
	),
	lesson(
		"charm-vanna",
		"structure",
		"Charm and vanna: exposure that changes without a trade",
		"Charm 与 Vanna：没有成交也会变化的敞口",
		"Separate how time and volatility change delta, even when no one trades.",
		"区分时间与波动率如何在无人交易时改变 Delta。",
		["C22"],
		["gamma", "theta-vega-rho"],
	),
	lesson(
		"portfolio-pnl",
		"portfolio",
		"P&L: positions, cost and cash",
		"盈亏：持仓、成本与现金",
		"Calculate position value and realized and unrealized P&L, and tell cash from buying power.",
		"计算持仓价值、已实现与未实现盈亏，并区分现金与购买力。",
		["C28"],
		["option-strategies"],
	),
	lesson(
		"portfolio-performance",
		"portfolio",
		"Performance: returns, win rate and drawdown",
		"绩效：收益、胜率与回撤",
		"Separate deposits from returns, and read win rate, profit factor and drawdown correctly.",
		"区分资金存取与收益，并正确理解胜率、盈利因子与回撤。",
		["C29"],
		["portfolio-pnl"],
	),
	lesson(
		"portfolio-exposure",
		"portfolio",
		"Portfolio Greeks: adding up exposure",
		"组合希腊值：汇总敞口",
		"Add up portfolio Greeks with the right signs and units, and show what is missing.",
		"用正确的符号与单位汇总组合希腊值，并标明缺失部分。",
		["C30"],
		["portfolio-pnl", "theta-vega-rho", "gamma", "expiration-settlement"],
	),
];
