export const courseModules = [
	{
		id: "orientation",
		path: "start",
		en: "Markets and options from zero",
		zh: "从零了解市场与期权",
	},
	{
		id: "contracts",
		path: "core",
		en: "Contracts and money",
		zh: "合约与金额",
	},
	{
		id: "execution",
		path: "core",
		en: "Quotes, executions and sentiment",
		zh: "报价、成交与情绪分类",
	},
	{
		id: "flow",
		path: "core",
		en: "Flow, positions and data quality",
		zh: "成交流、持仓与数据质量",
	},
	{
		id: "research",
		path: "core",
		en: "Comparison and investigation",
		zh: "比较与研究",
	},
	{
		id: "production",
		path: "core",
		en: "Produce and audit research",
		zh: "撰写与审核研究",
	},
	{
		id: "exposure",
		path: "models",
		en: "Greeks, volatility and exposure",
		zh: "希腊值、波动率与敞口",
	},
	{
		id: "structure",
		path: "models",
		en: "Modeled positioning and structure",
		zh: "模型持仓与结构",
	},
	{
		id: "portfolio",
		path: "portfolio",
		en: "Portfolio understanding",
		zh: "理解投资组合",
	},
	{
		id: "workflows",
		path: "workflows",
		en: "Workflows in TradingFlow",
		zh: "在 TradingFlow 中构建工作流",
	},
] as const;
/** The core path runs in lesson order; the three deeper branches follow it in any order. */
export const coursePaths = {
	start: {
		en: "Start here: no experience needed",
		zh: "从这里开始：无需任何基础",
	},
	core: { en: "Core path", zh: "核心路径" },
	models: {
		en: "Deeper branch: Greeks, volatility and structure",
		zh: "深入分支：希腊值、波动率与结构",
	},
	portfolio: { en: "Deeper branch: portfolios", zh: "深入分支：投资组合" },
	workflows: {
		en: "Deeper branch: workflows in TradingFlow",
		zh: "深入分支：在 TradingFlow 中构建工作流",
	},
} as const;
export type CoursePathId = keyof typeof coursePaths;

/**
 * Lessons 5–8 are also where experienced learners start, so they teach their ideas in full.
 * For learners coming from Start here, each names the earlier lesson and what it adds to it.
 */
export const buildsOn: Record<
	string,
	{ lessons: string[]; en: string; zh: string }
> = {
	"option-contracts": {
		lessons: ["trading-options"],
		en: "That lesson found a contract in a chain; this one names it exactly, turns its quote into dollars, and ties each price to a moment.",
		zh: "那一课在期权链中找到了合约；本课准确命名它，把报价换算成金额，并把每个价格对应到具体时刻。",
	},
	"option-rights": {
		lessons: ["what-options-are"],
		en: "That lesson met the holder and writer of one call; this one adds puts, opening versus closing, and who actually gets assigned.",
		zh: "那一课认识了一张看涨期权的持有人和义务方；本课加入看跌期权、开仓与平仓之分，以及究竟谁会被指派。",
	},
	"premium-payoff": {
		lessons: ["what-options-are", "options-risks"],
		en: "Those lessons showed a call's value at expiry and a writer's open-ended loss; this one splits a price into intrinsic and time value, finds the break-even, and works out both sides' results.",
		zh: "那两课展示了看涨期权到期时的价值，以及义务方没有上限的亏损；本课把价格拆成内在价值与时间价值，找出盈亏平衡点，并算出双方的结果。",
	},
	"expiration-settlement": {
		lessons: ["trading-options"],
		en: "That lesson listed the ways a position ends; this one shows what exercising early gives up, how share and cash settlement differ, and what can surprise you on expiry day.",
		zh: "那一课列出了持仓结束的几种方式；本课说明提前行权会放弃什么、股票交割与现金交割有何不同，以及到期日可能出现的意外。",
	},
};
export type ModuleId = (typeof courseModules)[number]["id"];

type Entry = {
	id: string;
	/** A checkpoint closes a module with questions on a new day; it has no practice unit. */
	kind?: "checkpoint";
	moduleId: ModuleId;
	title: string;
	titleZh: string;
	summary: string;
	summaryZh: string;
	concepts: string[];
	prerequisites: string[];
};
const lesson = (
	id: string,
	moduleId: ModuleId,
	title: string,
	titleZh: string,
	summary: string,
	summaryZh: string,
	concepts: string[],
	prerequisites: string[] = [],
): Entry => ({
	id,
	moduleId,
	title,
	titleZh,
	summary,
	summaryZh,
	concepts,
	prerequisites,
});
/** A module's closing checkpoint: its lessons' ideas applied, unguided, to a new day. */
const checkpoint = (
	moduleId: ModuleId,
	title: string,
	titleZh: string,
	summary: string,
	summaryZh: string,
	prerequisites: string[],
): Entry => ({
	id: `checkpoint-${moduleId}`,
	kind: "checkpoint",
	moduleId,
	title,
	titleZh,
	summary,
	summaryZh,
	concepts: [],
	prerequisites,
});
export const syllabus: readonly Entry[] = [
	lesson(
		"stocks-and-prices",
		"orientation",
		"Stocks and prices: what options are built on",
		"股票与价格：期权的基础",
		"Read a stock quote, see why you buy at the ask and sell at the bid, and tell a stock from an ETF and an index.",
		"读懂股票报价，理解为何按卖价买入、按买价卖出，并分清股票、ETF 与指数。",
		["C01", "C04"],
	),
	lesson(
		"what-options-are",
		"orientation",
		"Options: a paid right with a deadline",
		"期权：有期限的付费权利",
		"See what a call and a put give you, what the premium pays for, and the three common reasons people use options.",
		"理解看涨与看跌赋予的权利、权利金买到了什么，以及人们使用期权的三种常见原因。",
		["C02", "C03"],
		["stocks-and-prices"],
	),
	lesson(
		"trading-options",
		"orientation",
		"Trading an option: from chain to order",
		"交易期权：从期权链到下单",
		"Find one contract in an option chain, choose between market and limit orders, and see the ways a position ends.",
		"在期权链中找到一份合约，在市价单与限价单之间做出选择，并了解持仓的几种结束方式。",
		["C04", "C05"],
		["what-options-are"],
	),
	lesson(
		"options-risks",
		"orientation",
		"Risk first: how options lose money",
		"先看风险：期权如何亏钱",
		"See how a right call can still lose, why writers can lose far more than they collect, and how trading costs add up.",
		"理解为何方向对了仍可能亏钱、为何义务方的损失可能远超所收权利金，以及交易成本如何累积。",
		["C03", "C04", "C13"],
		["trading-options"],
	),
	checkpoint(
		"orientation",
		"Checkpoint: Start here, on a new day",
		"检查点：在新的一天里运用“从这里开始”",
		"Answer four questions on a Wednesday you haven't seen: sell shares at the quote, value a call from both sides, and place a limit order. Then see which lessons to revisit.",
		"在一个你没见过的周三回答四个问题：按报价卖出股票、从两方计算一张看涨的盈亏、下一张限价单。然后看看需要复习哪些课。",
		["options-risks"],
	),
	lesson(
		"option-contracts",
		"contracts",
		"Option contracts: what you are buying",
		"期权合约：你买的是什么",
		"Identify a contract from its underlying, type, strike and expiry, and turn a quoted price into dollars.",
		"从标的、类型、行权价与到期日识别一份合约，并把报价换算成金额。",
		["C01", "C02"],
	),
	lesson(
		"option-rights",
		"contracts",
		"Holders and writers: rights and obligations",
		"持有人与义务方：权利和义务",
		"See who holds the right, who carries the obligation, and how trading an option differs from exercising it.",
		"认清谁拥有权利、谁承担义务，以及交易期权与行权有何不同。",
		["C02", "C09"],
		["option-contracts"],
	),
	lesson(
		"premium-payoff",
		"contracts",
		"Premium, payoff and profit: both sides of the trade",
		"权利金、到期价值与盈亏：交易的两方",
		"Calculate premium, payoff and profit for the buyer and the writer, and see why in the money can still lose.",
		"计算买方与义务方的权利金、到期价值与盈亏，理解为何实值也可能亏损。",
		["C03"],
		["option-rights"],
	),
	lesson(
		"put-call-parity",
		"contracts",
		"Put-call parity: how calls, puts and shares line up",
		"看涨看跌平价：看涨、看跌与股票如何对齐",
		"Build 100 shares from a call and a put, price one option from the other, and check a print against parity before reading anything into it.",
		"用一张看涨和一张看跌组合出 100 股，由一个期权推出另一个的价格，并在解读一笔成交之前先用平价关系核对它。",
		["C39"],
		["premium-payoff"],
	),
	lesson(
		"expiration-settlement",
		"contracts",
		"Expiration: exercise, assignment and settlement",
		"到期：行权、指派与结算",
		"Tell closing from exercise and assignment, settle physical and cash contracts, and spot expiry-day surprises.",
		"区分平仓、行权与指派，完成实物与现金结算，并识别到期日的意外。",
		["C02", "C24"],
		["premium-payoff"],
	),
	checkpoint(
		"contracts",
		"Checkpoint: contracts and money, on a new day",
		"检查点：在新的一天里运用“合约与金额”",
		"Price contracts from a quote, follow an assignment, price a put from its call, and settle an index option in cash, all on a day you haven't seen.",
		"在你没见过的一天里：按报价计算合约成本、跟随一次指派、由看涨推出看跌的价格，并以现金结算一张指数期权。",
		["expiration-settlement"],
	),
	lesson(
		"quotes-orders-trades",
		"execution",
		"Quotes, orders and trades: three different events",
		"报价、订单与成交：三种不同事件",
		"Read bid, ask, sizes, spread and last without mistaking a quote for a fill.",
		"读懂买价、卖价、数量、价差与最新价，不把报价当成成交。",
		["C04"],
		["premium-payoff"],
	),
	lesson(
		"execution-counterparties",
		"execution",
		"Counterparties: who buys and who sells in one trade",
		"交易对手：同一笔成交中谁买谁卖",
		"Follow one incoming order into a resting order: two participants, one trade.",
		"追踪一张主动订单与挂单撮合：两方参与，一笔成交。",
		["C05"],
		["quotes-orders-trades"],
	),
	lesson(
		"execution-side",
		"execution",
		"Execution side: where a trade printed against the quote",
		"成交位置：成交价相对报价的位置",
		"Classify a trade as at the bid, inside the spread or at the ask, and know when the quote is too stale to tell.",
		"判断成交位于买价、价差内或卖价，并识别报价过旧、无法判断的情况。",
		["C06", "C24"],
		["execution-counterparties"],
	),
	lesson(
		"flow-sentiment",
		"execution",
		"Sentiment labels: when bullish or bearish is justified",
		"情绪标签：何时能称为看涨或看跌",
		"Learn when it is fair to call a trade bullish or bearish, and what that label cannot tell you.",
		"了解何时可以把一笔成交称为看涨或看跌，以及该标签无法说明什么。",
		["C07"],
		["execution-side"],
	),
	lesson(
		"option-strategies",
		"execution",
		"Strategies: one leg, many possible positions",
		"策略：一条腿，多种可能的持仓",
		"See how spreads, covered calls, collars and rolls change what one option leg means.",
		"看价差、备兑、领口与移仓如何改变单条期权腿的含义。",
		["C09"],
		["flow-sentiment"],
	),
	lesson(
		"multi-leg-structures",
		"execution",
		"Straddles, condors and multi-leg prints",
		"跨式、铁鹰与多腿成交",
		"Find a straddle's break-evens and an iron condor's worst case, and read four prints in one second as one package instead of four opinions.",
		"找出跨式的盈亏平衡点和铁鹰的最坏情况，并把同一秒内的四笔成交作为一个整体来读，而不是四个观点。",
		["C40"],
		["option-strategies"],
	),
	lesson(
		"validate-option-print",
		"execution",
		"Checking one trade: facts, inferences and unknowns",
		"核查一笔成交：事实、推断与未知",
		"Work through one trade from its evidence: premium, side, what is known and what to check next.",
		"从证据出发检查一笔成交：权利金、成交位置、已知信息与下一步检查。",
		["C03", "C06", "C07", "C24"],
		["option-strategies"],
	),
	checkpoint(
		"execution",
		"Checkpoint: quotes, executions and sentiment, on a new day",
		"检查点：在新的一天里运用“报价、成交与情绪分类”",
		"Place four prints against their quote, net their flow labels, price a spread printed as two legs, and tell a cancel from a trade, all on a day you haven't seen.",
		"在你没见过的一天里：对照报价给四笔成交定位、求它们成交流标签的净额、为打印成两条腿的价差定价，并区分撤单与成交。",
		["validate-option-print"],
	),
	lesson(
		"session-flow-vs-structure",
		"flow",
		"Volume and open interest: why they move differently",
		"成交量与未平仓量：为何变化不同",
		"See how opening, closing and transferred contracts move volume and open interest differently.",
		"理解开仓、平仓与转移如何让成交量与未平仓量发生不同变化。",
		["C08", "C24"],
		["validate-option-print", "expiration-settlement"],
	),
	lesson(
		"trade-records",
		"flow",
		"Tape rows: what one record represents",
		"成交记录：一行代表什么",
		"Rebuild size, premium and count from source prints, and follow duplicate and corrected messages.",
		"从原始成交还原数量、权利金与笔数，并追踪重复与更正消息。",
		["C10"],
		["execution-side"],
	),
	lesson(
		"execution-conditions",
		"flow",
		"Sweeps, blocks and complex orders: how a trade executed",
		"扫单、大宗与复杂订单：成交如何执行",
		"Read what sweep, block and multi-leg conditions say about how a trade executed, and what they leave unknown.",
		"读懂扫单、大宗与多腿条件说明了成交如何执行，以及仍然未知的部分。",
		["C11"],
		["trade-records"],
	),
	lesson(
		"unusual-activity",
		"flow",
		"Unusual activity: compared with what?",
		"异常成交：与什么相比？",
		"Compare activity with the right baseline, and see how a tiny denominator fakes a spike.",
		"用正确基准比较成交活跃度，并看清极小分母如何制造假异常。",
		["C12", "C25"],
		["session-flow-vs-structure"],
	),
	lesson(
		"symbol-drawer",
		"flow",
		"Data clocks: when each source was true",
		"数据时钟：每个来源在何时成立",
		"Check each field's source, time and coverage before combining data from different clocks.",
		"组合不同时间的数据前，先检查每个字段的来源、时间与覆盖。",
		["C24"],
		["session-flow-vs-structure"],
	),
	checkpoint(
		"flow",
		"Checkpoint: flow, positions and data quality, on a new day",
		"检查点：在新的一天里运用“成交流、持仓与数据质量”",
		"Work out a day's open interest from its record, a sweep's average price and a contract's relative volume, and check a record's date against what you need, all on a day you haven't seen.",
		"在你没见过的一天里：根据记录算出一天后的未平仓量、一次扫单的均价和一张合约的相对成交量，并对照要求核对记录的日期。",
		["symbol-drawer"],
	),
	lesson(
		"audited-boundary",
		"research",
		"Research questions: what evidence can answer",
		"研究问题：证据能回答什么",
		"Frame a question with a clear subject, measure and time window, and a reason to revisit it.",
		"提出对象、测量量与时间窗口都明确的问题，并说明何时需要重新审视。",
		["C26"],
		["symbol-drawer"],
	),
	lesson(
		"symbol-universe",
		"research",
		"Comparison groups: who belongs and who is missing",
		"比较范围：谁该纳入，谁缺失",
		"Decide from raw facts which names belong in a comparison, and keep missing ones visible.",
		"依据原始事实决定哪些标的进入比较，并让缺失项保持可见。",
		["C01", "C23", "C24"],
		["audited-boundary"],
	),
	lesson(
		"rank-symbols",
		"research",
		"Rankings: order without prediction",
		"排名：排序不等于预测",
		"Pick a ranking metric for your question, and see how peers can move a rank without new activity.",
		"为问题选择排名指标，并看同组变化如何在没有新成交时改变排名。",
		["C12", "C23"],
		["symbol-universe"],
	),
	lesson(
		"rank-contracts",
		"research",
		"Contract neighborhoods: strikes and expiries in context",
		"合约邻域：结合行权价与到期日来看",
		"Compare total activity and concentration across strikes and expiries before choosing a contract to inspect.",
		"选择要检查的合约前，先比较不同行权价与到期日的总成交与集中度。",
		["C03", "C23"],
		["rank-symbols"],
	),
	lesson(
		"point-in-time-research",
		"research",
		"Backtests: testing a pattern without hindsight",
		"回测：不带后见之明地检验模式",
		"Test an idea only on data you have not looked at, using what was known at the time.",
		"只用当时已知的信息，并只在未看过的数据上检验一个想法。",
		["C25", "C26"],
		["rank-contracts"],
	),
	checkpoint(
		"research",
		"Checkpoint: comparison and investigation, on a new day",
		"检查点：在新的一天里运用“比较与研究”",
		"Apply a comparison rule to five names, rank the survivors by the right metric, and age a recency score with no new trades, all on a day you haven't seen.",
		"在你没见过的一天里：对五个标的应用比较规则、按正确的指标给留下的标的排名，并在没有新成交时推算近期分数的衰减。",
		["point-in-time-research"],
	),
	lesson(
		"cookbook-research-packet",
		"production",
		"Research packets: work someone else can rerun",
		"研究包：他人可以重跑的工作",
		"Record inputs, calculations and exclusions so someone else can rerun your result.",
		"记录输入、计算与排除项，让他人能够重跑你的结果。",
		["C27"],
		["point-in-time-research"],
	),
	lesson(
		"market-recap",
		"production",
		"Recaps: claims your evidence supports",
		"复盘：证据支持的结论",
		"Build a headline, chart and caption that say only what the evidence supports.",
		"撰写只陈述证据所支持内容的标题、图表与图注。",
		["C27"],
		["cookbook-research-packet"],
	),
	lesson(
		"audit-market-recap",
		"production",
		"Audits: finding and repairing a flawed recap",
		"审核：发现并修复有缺陷的复盘",
		"Find the numerical and reasoning errors in someone else's recap, fix them, and keep what holds up.",
		"找出他人复盘中的数值与推理错误，加以修复，并保留成立的部分。",
		["C26", "C27"],
		["market-recap"],
	),
	checkpoint(
		"production",
		"Checkpoint: producing and auditing research, on a new day",
		"检查点：在新的一天里运用“撰写与审核研究”",
		"Total a packet with a missing row, catch a chart whose axis exaggerates, and audit a colleague's recap claim by claim, all on a day you haven't seen.",
		"在你没见过的一天里：为有一行缺失的研究包算出合计、识别夸大差距的坐标轴，并逐条审核同事的复盘。",
		["audit-market-recap"],
	),
	lesson(
		"delta",
		"exposure",
		"Delta: a local price sensitivity",
		"Delta：局部价格敏感度",
		"Estimate how an option's price moves for a small stock move, and get the position's sign right.",
		"估算标的小幅变动时期权价格的变化，并确定持仓的正负方向。",
		["C13"],
		["premium-payoff"],
	),
	lesson(
		"gamma",
		"exposure",
		"Gamma: how delta changes",
		"Gamma：Delta 如何变化",
		"See how delta itself changes as the stock moves, and what that means for a hedge.",
		"理解 Delta 如何随股价变化，以及这对对冲意味着什么。",
		["C13"],
		["delta"],
	),
	lesson(
		"theta-vega-rho",
		"exposure",
		"Theta, vega and rho: time, volatility and rates",
		"Theta、Vega 与 Rho：时间、波动率与利率",
		"Read time decay, volatility and rate sensitivity in their own units, and see how they can outweigh a good move.",
		"按各自单位读取时间损耗、波动率与利率敏感度，并看它们如何抵消有利的价格变动。",
		["C13"],
		["delta"],
	),
	lesson(
		"zero-dte",
		"exposure",
		"0DTE: options on their last day",
		"0DTE：最后一天的期权",
		"Watch a same-day option's value drain by the hour, see its delta swing on a few cents near the strike, and why its volume never shows up in open interest.",
		"观察当天到期的期权价值如何按小时流失，看它的 Delta 在行权价附近如何随几美分摆动，以及为何它的成交量永远不会出现在未平仓量里。",
		["C42"],
		["theta-vega-rho", "session-flow-vs-structure"],
	),
	lesson(
		"implied-realized-volatility",
		"exposure",
		"Implied and realized volatility: forward and backward views",
		"隐含与已实现波动率：向前与向后的视角",
		"Tell the volatility priced into options from the volatility the stock actually showed.",
		"区分期权价格中隐含的波动率与股票实际表现出的波动率。",
		["C14"],
		["theta-vega-rho"],
	),
	lesson(
		"expected-move",
		"exposure",
		"Expected move: the range options price in",
		"预期变动：期权定价的区间",
		"Turn implied volatility into a one-standard-deviation move, see why the straddle prices about 0.8 of it, and how often a stock ends outside the range.",
		"把隐含波动率换算成一个标准差的变动，理解为何跨式价格约为它的 0.8，以及股价收在区间之外有多常见。",
		["C41"],
		["implied-realized-volatility"],
	),
	lesson(
		"volatility-surface",
		"exposure",
		"The volatility surface: smile, skew and term structure",
		"波动率曲面：微笑、偏斜与期限结构",
		"Read implied volatility across strikes and expiries, and tell measured points from filled-in ones.",
		"按行权价与到期日读取隐含波动率，并区分实际观测与插值估计。",
		["C15"],
		["implied-realized-volatility"],
	),
	lesson(
		"iv-rank-percentile",
		"exposure",
		"IV rank and percentile: why they disagree",
		"IV Rank 与百分位：为何会不同",
		"Compute IV rank and IV percentile on the same history, and see why one outlier splits them.",
		"在同一历史上计算 IV Rank 与 IV 百分位，并看一个极端值为何让两者分歧。",
		["C16"],
		["implied-realized-volatility"],
	),
	lesson(
		"dex-dei-gex",
		"exposure",
		"DEX and DEI: flow in share-equivalents",
		"DEX 与 DEI：以股等价量衡量成交流",
		"Turn trades into share-equivalents and compare flow across stocks of different sizes.",
		"把成交换算成股等价量，并在规模不同的股票之间比较成交流。",
		["C17", "C18"],
		["delta", "unusual-activity"],
	),
	lesson(
		"gamma-exposure",
		"structure",
		"GEX: building a gamma exposure snapshot",
		"GEX：建立 Gamma 敞口快照",
		"Build a GEX snapshot from stated assumptions, and compare net, gross and local exposure.",
		"在明确假设下建立 GEX 快照，并比较净值、总幅度与局部敞口。",
		["C19"],
		["gamma", "volatility-surface", "symbol-drawer"],
	),
	lesson(
		"gamma-regimes",
		"structure",
		"Gamma regimes: hedging, not forecasting",
		"Gamma 状态：对冲，而非预测",
		"See how hedging flows differ above and below the zero-gamma level, without treating it as a forecast.",
		"理解零 Gamma 位置上下的对冲流有何不同，而不把它当作预测。",
		["C20"],
		["gamma-exposure"],
	),
	lesson(
		"structural-levels",
		"structure",
		"Walls and max pain: reference levels, not targets",
		"墙位与最大痛点：参考位置，不是目标",
		"Tell gamma walls from max pain, and measure distance in dollars, percent and ATR.",
		"区分 Gamma 墙位与最大痛点，并用美元、百分比与 ATR 衡量距离。",
		["C21"],
		["gamma-exposure"],
	),
	lesson(
		"charm-vanna",
		"structure",
		"Charm and vanna: exposure that changes without a trade",
		"Charm 与 Vanna：没有成交也会变化的敞口",
		"Separate how time and volatility change delta, even when no one trades.",
		"区分时间与波动率如何在无人交易时改变 Delta。",
		["C22"],
		["gamma", "theta-vega-rho"],
	),
	lesson(
		"portfolio-pnl",
		"portfolio",
		"P&L: positions, cost and cash",
		"盈亏：持仓、成本与现金",
		"Calculate position value and realized and unrealized P&L, and tell cash from buying power.",
		"计算持仓价值、已实现与未实现盈亏，并区分现金与购买力。",
		["C28"],
		["option-strategies"],
	),
	lesson(
		"portfolio-performance",
		"portfolio",
		"Performance: returns, win rate and drawdown",
		"绩效：收益、胜率与回撤",
		"Separate deposits from returns, and read win rate, profit factor and drawdown correctly.",
		"区分资金存取与收益，并正确理解胜率、盈利因子与回撤。",
		["C29"],
		["portfolio-pnl"],
	),
	lesson(
		"portfolio-exposure",
		"portfolio",
		"Portfolio Greeks: adding up exposure",
		"组合希腊值：汇总敞口",
		"Add up portfolio Greeks with the right signs and units, and show what is missing.",
		"用正确的符号与单位汇总组合希腊值，并标明缺失部分。",
		["C30"],
		["portfolio-pnl", "theta-vega-rho", "gamma", "expiration-settlement"],
	),
	lesson(
		"tradingflow-recipes",
		"workflows",
		"Recipes: research that re-runs on fresh data",
		"Recipe：在新数据上重跑的研究",
		"Pick a TradingFlow recipe by the question it answers, read which session a run shows, and see why the official version never changes under you.",
		"按要回答的问题选择 TradingFlow Recipe，看清一次运行展示的是哪个交易时段，并理解为何官方版本不会在你脚下改变。",
		["C31"],
		["cookbook-research-packet"],
	),
	lesson(
		"recipe-map",
		"workflows",
		"Read a recipe like an auditor",
		"像审计员一样读 Recipe",
		"Trace a report's sentences through the recipe map, tell text written into the recipe from text computed for the session, and keep a top-N table apart from the whole screen.",
		"通过 Recipe 地图追溯报告中的句子，分清写进 Recipe 的文字与针对交易时段算出的文字，并把前 N 名表格与整个筛选结果区分开。",
		["C31", "C32"],
		["tradingflow-recipes"],
	),
	lesson(
		"recipe-inputs",
		"workflows",
		"Change the inputs, keep the question",
		"改输入，不改问题",
		"See why an edited input does nothing until you run it, tell a re-run of the same question from a new one, and watch a thin contract take over when the floors drop.",
		"理解为何修改的输入在运行前不起作用，分清重跑同一个问题与提出新问题，并观察门槛降低后冷门合约如何占据榜首。",
		["C31", "C33"],
		["recipe-map"],
	),
	lesson(
		"research-checklist",
		"workflows",
		"Start from a research checklist",
		"从研究清单开始",
		"Turn a decision into steps a tool can check, keep the checklist you build before Home resets it, and see what Customize with AI does before it proposes anything.",
		"把一个决定变成工具能核查的步骤，在 Home 重置前保存你建立的清单，并了解 Customize with AI 在提出建议之前会做什么。",
		["C33", "C34"],
		["recipe-inputs"],
	),
	lesson(
		"ai-verify",
		"workflows",
		"Ask TradingFlow AI, then verify",
		"问 TradingFlow AI，然后核查",
		"Sort an AI answer into what the report shows, what you can calculate and what goes beyond the data, count the credits a conversation uses, and tell AI Insight from Edit with AI.",
		"把 AI 的回答分成报告中有的、能算出来的和超出数据的，算清一段对话消耗的积分，并分清 AI Insight 与 Edit with AI。",
		["C34", "C35"],
		["research-checklist"],
	),
	lesson(
		"custom-formulas",
		"workflows",
		"Build your own Rank column",
		"构建你自己的 Rank 列",
		"Write a Rank Symbols formula column whose units make sense, keep thin rows from leading it, and know what a Rank View saves.",
		"在 Rank Symbols 上写一个单位合理的公式列，不让单薄的行领跑，并了解 Rank View 保存了什么。",
		["C35", "C36"],
		["ai-verify", "rank-symbols"],
	),
	lesson(
		"edit-with-ai",
		"workflows",
		"Fork or write a recipe with AI",
		"用 AI 分叉或编写 Recipe",
		"Scope an AI edit so you can review it, undo a change you didn't ask for, and save a private recipe on purpose.",
		"给 AI 修改划定范围以便审阅，撤销你没要求的改动，并有意识地保存私有 Recipe。",
		["C36", "C37"],
		["custom-formulas"],
	),
	lesson(
		"connect-agent",
		"workflows",
		"Connect your own AI agent",
		"连接你自己的 AI 智能体",
		"Connect Claude or another agent to TradingFlow's read-only tools, prove the connection yourself, and know what a key can and can't do.",
		"把 Claude 或其他智能体连接到 TradingFlow 的只读工具，亲自证明连接成功，并了解一把密钥能做什么、不能做什么。",
		["C37", "C38"],
		["edit-with-ai"],
	),
];
